# 当有改动推送到master分支时，启动Action
name: 自动部署

on:
  push:
    branches:
      - main

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x" #action使用的node版本，建议大版本和本地保持一致。可以在本地用node -v查询版本号。

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g

    - name: 缓存 Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --save
        npm i hexo-renderer-pug hexo-renderer-stylus hexo-tag-aplayer hexo-abbrlink hexo-butterfly-envelope hexo-lazyload-image hexo-butterfly-wowjs hexo-butterfly-swiper hexo-butterfly-tag-plugins-plus hexo-filter-fcircle-anzhiyu hexo-generator-search --s

    - name: 生成静态文件
      run: |
        hexo clean
        hexo g

    - name: 部署 #此处master:master 指从本地的master分支提交到远程仓库的master分支，若远程仓库没有对应分支则新建一个。如有其他需要，可以根据自己的需求更改。
      run: |
        cd ./public
        git init
        git config --global user.name '${{ secrets.GITHUBUSERNAME }}'
        git config --global user.email '${{ secrets.GITHUBEMAIL }}'
        git add .
        git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By Github Actions"
        git push --force --quiet "https://timigomen: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@github.com/timigomen/timigomen.github.io.git" main:main